# Generated by Django 4.1.7 on 2023-04-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_alter_user_created_alter_user_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='phone',
        ),
    ]
