# Generated by Django 4.1.7 on 2023-05-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0004_user_total_cameras'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_license_plates',
            field=models.IntegerField(default=0),
        ),
    ]
