# Generated by Django 4.1.7 on 2023-06-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_license_plate', '0002_licenseplate_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseplate',
            name='frame',
            field=models.ImageField(default='/media/default_images/default_lp.png', upload_to='media/license_plates/'),
        ),
    ]
