# Generated by Django 4.1.7 on 2023-06-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_license_plate', '0003_licenseplate_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseplate',
            name='frame',
            field=models.ImageField(default='default_images/default_lp.png', upload_to='license_plates/'),
        ),
    ]
